name: Create terraform code

on:
    push:
        branches:
            - featurebr

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v5.0.0

        - name: Az Login
          uses: Azure/login@v2.3.0
          with: 
            creds: ${{SECRETS.CREDENTIALS}}

        - name: Setup Terraform Hashicorp
          uses: hashicorp/setup-terraform@v2.0.3
      
        - name: Initialize Terraform
          run: terraform init

        - name: Validate Terraform
          run: terraform validate

        - name: Plan Terraform
          run: terraform plan

        - name: Apply Terraform
          run: terraform apply -auto-approve
